#!/bin/bash

# The script reads fasta files from FASTA directory and calls 'shuffle_seq'
# script with each fasta file in order to generate background (control)
# sequence set.

# Program call: ./generate_control

FASTA_FILES=../../Inputs/FASTA/*.fasta;
SHUFFLED_FILES=../../Inputs/Shuffled_FASTA;

for file in ${FASTA_FILES};
do
    printf '\n'
    printf '=%.0s' {1..80}
    printf '\n'
    filename=$(basename ${file});
    echo "Reading ${filename}..."
    ./shuffle_seq ${file}
    generated_sequences=`tail -n 2 ${SHUFFLED_FILES}/$filename |
                            perl -ne 'print "$1\n" if /^>([0-9]+)\n$/'`
    echo "Generated sequence count = $generated_sequences."
done