## Tbx5 transcription factor analysis (continuation)

```{r Libraries}
# Loading used libraries:
library(pacman)
p_load(data.table, rtracklayer, ggplot2, ggthemes, reshape2, dplyr, Biostrings)
```

```{r Paths}
# nolint start
# Declaring paths:
TBX5_FOLDER <- "/home/daniele/Desktop/IV_course/I_semester/Kursinis_projektas/Tbx5_analysis_cont"       
INTERMEDIATE_FILES <- paste0(TBX5_FOLDER, "/Intermediate_data_files/") 
INPUTS <- paste0(TBX5_FOLDER, "/Inputs/")                              
FASTAs <- paste0(INPUTS, "FASTA/")                                     
MOTIFS <- paste0(TBX5_FOLDER, "/Motifs/")                              
CONTROL_SEQ <- paste0(INPUTS, "Shuffled_FASTA/")                       
FASTA_LIST <- list.files(path = FASTAs, "*fasta")                      
MOTIF_HITS <- paste0(INTERMEDIATE_FILES, "Motif_hits_tables/")         
TARGET_CONTROL <- c(FASTAs, CONTROL_SEQ)                               
COLUMN <- c("target", "background")
# nolint end
```

```{r Samples}
# Reading sample table:
samples <- read.csv(file = paste0(INTERMEDIATE_FILES, "sample_key.csv"))
```

```{r Motif_hits}
# nolint start
# Calculating scores for each .fasta file:
for (filename in seq(1, length(FASTA_LIST))) {
    # Creating an empty matrix and setting it's column names:
    pwm_results <- matrix(ncol = 2, nrow = 10) %>%
                `colnames<-`(c("target", "background"))
    
    # Basenaming .fasta file and declaring a full path of the file:
    file <- tools::file_path_sans_ext(FASTA_LIST[filename])

    # Getting a list of the motif filenames:
    MOTIF_LIST <- list.files(path = paste0(MOTIFS, file, "/"), "*motif")

    # Setting rownames for 'pwm_results' matrix:
    rownames(pwm_results) <-
            c(paste0(tools::file_path_sans_ext(MOTIF_LIST), ".m"))

    # Iterating motif list:
    for (motif in seq(MOTIF_LIST)) {
        print(paste("START TIME: ", format(Sys.time(), "%b %d %X %Y"),
                    ", MOTIF NAME: ", MOTIF_LIST[[motif]]))

        # Performing calculations for both target and control sequence sets:
        for (column in seq(COLUMN)) {
            # Reading a PWM matrix for certain motif:
            pwm <- read.table(paste0(MOTIFS, file, "/", MOTIF_LIST[[motif]]))
            t_pwm <- t(pwm) %>% `rownames<-`(c("A", "C", "G", "T"))

            # Loading .fasta file sequences into an XStringSet object:
            seq_object <- readDNAStringSet(paste0(TARGET_CONTROL[column],
                                                  FASTA_LIST[filename]))
            pwm_match <- 0

            # Iterating XStringSet object elements and counting motif hits:
            for (i in seq(seq_object)) {
                target_hits <- matchPWM(as.matrix(t_pwm), seq_object[[i]],
                                min.score = "80%", with.score = TRUE)

                # Getting motif hit score and checking whether it is finite.
                # If the score is 'Inf' it means that the hit was not found
                # and 'target_hits' variable outputs 'None' next to the label
                # 'views' instead of printing hit start and end positions:
                core_score <- min(mcols(target_hits)$score / maxScore(t_pwm))
                if (is.finite(core_score)) {
                    pwm_match <- pwm_match + 1
                    if (pwm_match %% 800 == 0) {
                        print(paste0("Column = ", column,
                                     ". Value = ", pwm_match))
                    }
                } else { next }
            }

            # Storing total motif hit count at the particular matrix cell and
            # writing the result into a file:
            pwm_results[motif, column] <- pwm_match
            write.table(pwm_results, paste0(MOTIF_HITS, file))
            print(paste("END TIME: ", format(Sys.time(), "%b %d %X %Y")))
        }
    }
    print(paste("END TIME: ", format(Sys.time(), "%b %d %X %Y")))
}
# nolint end
```

```{r Chi-Square_Test}
# nolint start
# Running Chi-square test in order to determine if there is a significant
# relationship between two categorical variables (target and background):
for (filename in seq(1, length(FASTA_LIST))) {
    file <- tools::file_path_sans_ext(FASTA_LIST[filename])
    full_path <- file.path(MOTIF_HITS, paste0(file, ".csv"))

    if (file.exists(full_path)) {
        table <- read.csv(full_path)
        rownames(table) <- table[, 1]
        table$motif_name <- NULL

        # If the p-value is below 0.05, the null hypothesis can be rejected:
        chi_test <- chisq.test(table)
        print(chi_test) # p-value < 2.2e-16
    } else { next }    
}
# A p-value is a probability, a number between 0 and 1, calculated after
# running a statistical test on data. A small p-value (< 0.05 in general)
# means that the observed results are so unusual assuming that they
# were due to chance only.
# nolint end
```
